# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_proto import agent_pb2 as agent__proto_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_proto/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """文件准备与单轮问答共享资源契约，但可由两个独立 gRPC 服务进程部署。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_stream(
                '/traceagent.v1.AgentService/ChatCompletion',
                request_serializer=agent__proto_dot_agent__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=agent__proto_dot_agent__pb2.CompletionEvent.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """文件准备与单轮问答共享资源契约，但可由两个独立 gRPC 服务进程部署。
    """

    def ChatCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=agent__proto_dot_agent__pb2.ChatCompletionRequest.FromString,
                    response_serializer=agent__proto_dot_agent__pb2.CompletionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'traceagent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('traceagent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """文件准备与单轮问答共享资源契约，但可由两个独立 gRPC 服务进程部署。
    """

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/traceagent.v1.AgentService/ChatCompletion',
            agent__proto_dot_agent__pb2.ChatCompletionRequest.SerializeToString,
            agent__proto_dot_agent__pb2.CompletionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DocumentResourceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareResources = channel.unary_unary(
                '/traceagent.v1.DocumentResourceService/PrepareResources',
                request_serializer=agent__proto_dot_agent__pb2.PrepareResourcesRequest.SerializeToString,
                response_deserializer=agent__proto_dot_agent__pb2.PrepareResourcesResponse.FromString,
                _registered_method=True)
        self.ReadBlocks = channel.unary_unary(
                '/traceagent.v1.DocumentResourceService/ReadBlocks',
                request_serializer=agent__proto_dot_agent__pb2.ReadBlocksRequest.SerializeToString,
                response_deserializer=agent__proto_dot_agent__pb2.ReadBlocksResponse.FromString,
                _registered_method=True)


class DocumentResourceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PrepareResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentResourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareResources': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareResources,
                    request_deserializer=agent__proto_dot_agent__pb2.PrepareResourcesRequest.FromString,
                    response_serializer=agent__proto_dot_agent__pb2.PrepareResourcesResponse.SerializeToString,
            ),
            'ReadBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlocks,
                    request_deserializer=agent__proto_dot_agent__pb2.ReadBlocksRequest.FromString,
                    response_serializer=agent__proto_dot_agent__pb2.ReadBlocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'traceagent.v1.DocumentResourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('traceagent.v1.DocumentResourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentResourceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traceagent.v1.DocumentResourceService/PrepareResources',
            agent__proto_dot_agent__pb2.PrepareResourcesRequest.SerializeToString,
            agent__proto_dot_agent__pb2.PrepareResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traceagent.v1.DocumentResourceService/ReadBlocks',
            agent__proto_dot_agent__pb2.ReadBlocksRequest.SerializeToString,
            agent__proto_dot_agent__pb2.ReadBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
